export const fakeAppointments = [
  {
    id: 1,
    name: "Juan Dela Cruz",
    email: "juan@gmail.com",
    date: "2026-05-10",
    status: "pending",
    total_price: 500,
  },
  {
    id: 2,
    name: "Maria Santos",
    email: "maria@gmail.com",
    date: "2026-05-12",
    status: "approved",
    total_price: 800,
  },
  {
    id: 3,
    name: "Pedro Reyes",
    email: "pedro@gmail.com",
    date: "2026-05-08",
    status: "cancelled",
    total_price: 300,
  },
  {
    id: 4,
    name: "Ana Lopez",
    email: "ana@gmail.com",
    date: "2026-05-15",
    status: "pending",
    total_price: 1000,
  },
  {
    id: 5,
    name: "Carlos Gomez",
    email: "carlos@gmail.com",
    date: "2026-05-20",
    status: "approved",
    total_price: 1200,
  },
  {
    id: 6,
    name: "Liza Cruz",
    email: "liza@gmail.com",
    date: "2026-05-18",
    status: "pending",
    total_price: 700,
  },
  {
    id: 7,
    name: "Mark Aquino",
    email: "mark@gmail.com",
    date: "2026-05-25",
    status: "approved",
    total_price: 900,
  },
  {
    id: 8,
    name: "Sofia Lim",
    email: "sofia@gmail.com",
    date: "2026-05-22",
    status: "cancelled",
    total_price: 400,
  },
  {
    id: 9,
    name: "Daniel Tan",
    email: "daniel@gmail.com",
    date: "2026-05-28",
    status: "pending",
    total_price: 1500,
  },
  {
    id: 10,
    name: "Grace Lee",
    email: "grace@gmail.com",
    date: "2026-05-30",
    status: "approved",
    total_price: 1100,
  },
];